# Generated by Django 4.0.1 on 2022-03-01 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_firstname_profile_lastname_profile_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Firstname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Lastname',
            new_name='lastname',
        ),
    ]
