# Generated by Django 4.0.1 on 2022-01-31 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_tanks_tanks'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_tanks',
            name='Country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.country'),
        ),
        migrations.AddField(
            model_name='tanks',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category_tanks'),
        ),
    ]
