# Generated by Django 4.0.1 on 2022-01-31 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_category_tanks_country_category_tanks_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_tanks',
            name='Country',
        ),
        migrations.AddField(
            model_name='category_tanks',
            name='Country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.country'),
        ),
    ]
