# Generated by Django 4.0.1 on 2022-01-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_category_tanks_country_category_tanks_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tanks',
            name='category',
        ),
        migrations.AddField(
            model_name='tanks',
            name='category',
            field=models.ManyToManyField(null=True, to='shop.Category_Tanks'),
        ),
    ]
