# Generated by Django 4.0.1 on 2022-02-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_fuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
