# Generated by Django 4.0.1 on 2022-02-27 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_fuel_tanks_delete_products_fuel_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category_Shop',
        ),
    ]
