# Generated by Django 4.0.1 on 2022-02-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_fuel_category_fuel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuel',
            name='category',
        ),
        migrations.AddField(
            model_name='fuel',
            name='category',
            field=models.ManyToManyField(null=True, to='shop.Tanks'),
        ),
    ]
