# Generated by Django 4.0.1 on 2022-02-27 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_remove_fuel_category_fuel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuel',
            name='category',
        ),
        migrations.AddField(
            model_name='fuel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.tanks'),
        ),
    ]
