# Generated by Django 4.0.1 on 2022-03-12 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_remove_fuel_category_fuel_category'),
        ('orders', '0004_order_paid_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_fuels',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.fuel'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_tanks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.tanks'),
        ),
    ]
