# Generated by Django 4.0.1 on 2022-03-13 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_orderitem_product_orderitem_product_fuels_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_fuels',
        ),
    ]
