# Generated by Django 4.0.1 on 2022-03-13 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_orderitem_product_fuels'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
