# Generated by Django 4.0.1 on 2022-03-13 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_remove_fuel_category_fuel_category'),
        ('orders', '0009_rename_product_orderitem_product_tanks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_tanks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.tanks'),
        ),
    ]
